[workspace]
members = [
    "helix-auth-lib",
    "helix-config-lib",
    "helix-tracker-lib",
]

##DEFAULT RUNNING BIN


##__FIX FOR ARM COMPILATION SINCE RUST 1.38
[profile.release]
codegen-units = 1